language: python
python: 3.6
branches: master
install:
- pip install mkdocs mkdocs-material pygments pymdown-extensions
script: true
before_script:
  - "yarn global add firebase-tools"
  - "mkdocs build --verbose --clean --strict"
  - "mv ./site ./public"
after_success:
  - "firebase deploy --token=${FIREBASE_API_TOKEN}"