site_name: saladbot API
theme:
  name: 'material'
  palette:
    primary: 'purple'
    accent: 'purple'
  logo:
    icon: 'help'
  favicon: 'assets/images/favicon.ico'
repo_name: 'Kore-Development/saladbot-api'
repo_url: 'https://github.com/Kore-Development/saladbot-api'
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://cdn.jsdelivr.net/gh/Kore-Development/saladbot-api@master/docs/javascripts/https.js'
